#!/usr/bin/python
import tarfile
import os
import json
import urllib2
import io
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('command',nargs='+')
parser.add_argument("-f", "--file", help="install from file", default=False,
                    action="store")
args = parser.parse_args()

if args.file and args.command[0] != "install":
    exit("Cannot uninstall from a file!")

if args.file and len(args.command) > 1:
    exit("Specify either a file or a package name!")

gimp_plugins_dir = "/home/tschuy/.gimp-2.8/plug-ins/"
host = "http://localhost/"

def plugin_config_file(plugin_name):
    return gimp_plugins_dir + '.' + plugin_name

def install(tar, manifest, filename):
    print("Installing " + manifest['name'] + " from " + filename)

    with open(plugin_config_file(manifest['identifier']), 'w') as f:
        files = [t for t in tar if t.name != 'gpi.json']
        plugin_info = {
            'version': manifest['version'],
            'name': manifest['name'],
            'files': [file.name for file in files]
        }
        f.write(json.dumps(plugin_info))

    tar.extractall(gimp_plugins_dir, members=files)
    print(manifest['name'] + " " + manifest['version'] + " installed successfully!")


def uninstall(config):
    with open(config, 'r') as f:
        data = json.load(f)

        directories = []
        for file in data['files']:
            if os.path.isdir(gimp_plugins_dir + file):
                directories.append(gimp_plugins_dir + file)
            else:
                os.remove(gimp_plugins_dir + file)

        # TODO remove empty directories
        os.remove(config)

    print(data['name'] + " " + data['version'] + " uninstalled successfully!")


if args.command[0] == "install":
    if args.file:
        if not tarfile.is_tarfile(args.file):
            exit("File must be a tarfile!")
        t = tarfile.open(args.file, 'r')
        filename = args.file
    else:
        response = urllib2.urlopen(host + args.command[1] + '.tar.gz')
        t=tarfile.open(fileobj=io.BytesIO(response.read()), mode='r')
        filename = host + args.command[1] + '.tar.gz'

    manifest = json.load(t.extractfile('gpi.json'))
    install(t, manifest, filename)

elif args.command[0] == "uninstall":
    config = plugin_config_file(args.command[1])
    if not os.path.isfile(config):
        exit(plugin_name + " is not installed!")
    uninstall(config)
