#!/usr/bin/python
import tarfile
import sys
import os
import json
import urllib2
import io

gimp_plugins_dir = "/home/tschuy/.gimp-2.8/plug-ins/"
host = "http://localhost/"

def plugin_config_file(plugin_name):
    return gimp_plugins_dir + '.' + plugin_name


if sys.argv[1] == "install":
    if sys.argv[2] == "-f":
        filename = sys.argv[3]
        if not tarfile.is_tarfile(filename):
            exit("File must be a tarfile!")
        t = tarfile.open(filename, 'r')
    else:
        response = urllib2.urlopen(host + sys.argv[2] + '.tar.gz')
        t=tarfile.open(fileobj=io.BytesIO(response.read()), mode='r')
        filename = host + sys.argv[2] + '.tar.gz'

    manifest = json.load(t.extractfile('gpi.json'))
    print("Installing " + manifest['name'] + " from " + filename)

    with open(plugin_config_file(manifest['identifier']), 'w') as f:
        plugin_info = {
            'version': manifest['version'],
            'name': manifest['name'],
            'files': t.getnames()
        }
        f.write(json.dumps(plugin_info))

    t.extractall(gimp_plugins_dir)
    print(manifest['name'] + " " + manifest['version'] + " installed successfully!")

elif sys.argv[1] == "uninstall":
    config = plugin_config_file(sys.argv[2])
    if not os.path.isfile(config):
        exit(plugin_name + " is not installed!")

    with open(config, 'r') as f:
        data = json.load(f)

        directories = []
        for file in data['files']:
            if os.path.isdir(gimp_plugins_dir + file):
                directories.append(gimp_plugins_dir + file)
            else:
                os.remove(gimp_plugins_dir + file)

        # TODO remove empty directories
        os.remove(config)

    print(data['name'] + " " + data['version'] + " uninstalled successfully!")
