#!/usr/bin/python
import tarfile
import sys
import os
import json

plugin_name = sys.argv[2]

gimp_plugins_dir = "/home/tschuy/.gimp-2.8/plug-ins/"

plugin_config_file = gimp_plugins_dir + '.' + plugin_name


if sys.argv[1] == "install":

    if plugin_name == "imguruploader":
        filename = "/home/tschuy/imgur-uploader.tar.gz"

    if not tarfile.is_tarfile(filename):
        exit("File must be a tarfile!")
    t = tarfile.open(filename, 'r')

    manifest = json.load(t.extractfile('gpi.json'))

    with open(plugin_config_file, 'w') as f:
        plugin_info = {
            'version': manifest['version'],
            'name': manifest['name'],
            'files': t.getnames()
        }
        f.write(json.dumps(plugin_info))

    t.extractall(gimp_plugins_dir)
    print(manifest['name'] + " " + manifest['version'] + " installed successfully!")

elif sys.argv[1] == "uninstall":
    if not os.path.isfile(plugin_config_file):
        exit(plugin_name + " is not installed!")

    with open(plugin_config_file, 'r') as f:
        data = json.load(f)

        directories = []
        for file in data['files']:
            if os.path.isdir(gimp_plugins_dir + file):
                directories.append(gimp_plugins_dir + file)
            else:
                os.remove(gimp_plugins_dir + file)

        # TODO remove empty directories
        os.remove(plugin_config_file)

    print(data['name'] + " " + data['version'] + " uninstalled successfully!")
