#!/bin/sh

/usr/bin/env python2 "$(git rev-parse --show-toplevel)"/setup.py test
if [ $? -ne 0 ]; then
	return 1
fi

if hash flake8 2>/dev/null; then
    /usr/bin/env flake8 "$(git rev-parse --show-toplevel)"
    if [ $? -ne 0 ]; then
        return 1
    fi
fi

return 0
